server:
  port: 8083

spring:
  application:
    name: money-service
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MONEY_DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
    baseline-on-migrate: false
    locations: classpath:migration

kafka:
  clusters:
    bootstrapservers: ${KAFKA_CLUSTERS_BOOTSTRAPSERVERS}

task:
  topic: ${TASK_TOPIC}
  result:
    topic: ${TASK_RESULT_TOPIC}

logging:
  topic: ${LOGGING_TOPIC}